name: Deploy Base Infrastructure on AWS

on:
  push:
    branches:
      - develop

env:
  ENVIRONMENT: dev

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    name: Deploy Base Infrastructure on AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: us-east-1

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.ENVIRONMENT }}-Base-Infraestructure-Stack
          template: template.yml
          parameter-overrides: "Environment=${{ env.ENVIRONMENT }}"